name = "natter-api"
main = "src/index.ts"
compatibility_date = "2026-05-15"
workers_dev = true

[[routes]]
pattern = "api.natter.akaaku.net"
custom_domain = true

[vars]
ACCOUNT_URL = "https://account.akaaku.net/"
APP_ID = "natter"
FRONTEND_URLS = "http://localhost:3000,http://127.0.0.1:3000,https://natter.akaaku.net"
SESSION_KID = "2026-04"

[[d1_databases]]
binding = "DB"
database_name = "natter"
database_id = "4caad066-71dc-49fe-a9e5-2e17f820f947"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "natter-assets"
